#version: "3.3"

services:
  jupyter:
    # you can change this to whatever you want.
    container_name: ganime
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./:/GANime"
    ports:
      - "8888:8888"
    command: jupyter lab --allow-root --ip="*" --token=easy
    #command: jupyter nbconvert --execute --to notebook /GANime/notebooks/model/vq-gan/min_gpt.ipynb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  tensorboard:
    image: tensorflow/tensorflow:2.7.0
    container_name: tensorboard
    volumes:
      - "./logs/ganime:/logs/ganime"
    ports:
      - "6007:6006"
    command: tensorboard --logdir=/logs/ganime --bind_all
