model:
  # checkpoint_path: ../../../checkpoints/kny_image_vgg19/checkpoint
  vqvae_config:
    beta: 0.25
    num_embeddings: 50257
    embedding_dim: 256
  autoencoder_config:
    z_channels: 256
    channels: 32
    channels_multiplier: 
    - 4
    - 8 
    - 8
    num_res_blocks: 1
    attention_resolution: 
    - 16
    resolution: 128
    dropout: 0.1
  discriminator_config:
    num_layers: 3
    filters: 64
    
  loss_config:
    discriminator:
      loss: "hinge"
      factor: 1.0
      iter_start: 53000
      weight: 1.0
    vqvae:
      codebook_weight: 1.0
      perceptual_weight: 4.0
    perceptual_loss: "vgg19" # "vgg16", "vgg19", "style"

trainer:
  batch_size: 32
  n_epochs: 2000
  gen_lr: 3e-5
  disc_lr: 3e-5
  gen_beta_1: 0.5
  gen_beta_2: 0.9
  disc_beta_1: 0.5
  disc_beta_2: 0.9
  gen_clip_norm: 1.0
  disc_clip_norm: 1.0

