model:
  transformer_config:
    vocab_size: 50257
    n_positions: 1024
    n_embd: 768
    n_layer: 12
    n_head: 12
    resid_pdrop: 0.1
    embd_pdrop: 0.1
    attn_pdrop: 0.1
  first_stage_config:
    checkpoint_path: ../../../checkpoints/mnist_image/checkpoint
    vqvae_config:
      beta: 0.25
      num_embeddings: 128
      embedding_dim: 128
    autoencoder_config:
      z_channels: 128
      channels: 128
      channels_multiplier: 
      - 1
      - 1 
      - 2
      - 2
      num_res_blocks: 1
      attention_resolution: 
      - 16
      resolution: 128
      dropout: 0.0
    discriminator_config:
      num_layers: 3
      filters: 64
      
    loss_config:
      discriminator:
        loss: "hinge"
        factor: 1.0
        iter_start: 10000
        weight: 0.3
      vqvae:
        codebook_weight: 1.0

train:
  batch_size: 32
  n_epochs: 150
  len_x_train: 8000
  warmup_epoch_percentage: 0.15
  lr_start: 1e-5
  lr_max: 2.5e-4
